# Generated by Django 4.0.5 on 2022-06-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=20)),
                ('sSex', models.CharField(default='M', max_length=2)),
                ('sEmail', models.CharField(blank=True, default='', max_length=100)),
                ('sPhone', models.CharField(blank=True, default='', max_length=50)),
                ('sAddr', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
