# Generated by Django 4.0.5 on 2022-06-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sAddr',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sEmail',
        ),
    ]
